language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t barbarajacob/docker -f Dockerfile.dev .

script:
  - docker run -e CI=true barbarajacob/docker npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-eu-west-2-294552318948"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
